import Header from "@/components/Header";
import ReactQueryProviders from "@/hooks/useReactQuery";
import { QueryClient } from "@tanstack/react-query";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "bballang",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();
/*
  Q. provider 로 랩핑하면 리액트 쿼리를 모든 페이지에서 사용할 수는 있겠지만,
  children 에 해당하는 페이지 컴포넌트들이 csr 이 되는 것 같은데..?
  ssr 이나 ssg 로 페이지가 렌더링 되어야하는 것들은 어떻게 되는건지 그럼..?
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <ReactQueryProviders>
          <Header />
          {children}
        </ReactQueryProviders>
      </body>
    </html>
  );
}
